# Generated by Django 3.2.4 on 2021-07-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamescategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
